name: 'Github Issues Digest'

description: 'Provide a summary of Github issues for a repository'

inputs:
  secret:
    description: 'PAT or github token to use for authentication. Defaults to GITHUB_TOKEN'
    default: ${{ github.token }}
    required: false
  repo:
    description: 'Repository to monitor in the format of owner/repo, defaults to the current repository'
    required: false
  save:
    description: 'directory to save the digest setting file, defaults to .github/digests'
    required: false
    default: ".github/digests"

branding:
  icon: 'align-justify'
  color: 'blue'

runs:
  using: 'composite'

  steps:
    - name: Setup Python
      uses: actions/setup-python@v3.1.4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: pip install -r ${{ github.action_path }}/requirements.txt
      shell: bash

    - name: Checkout code
      uses: actions/checkout@v3.5.2

    - name: Run script
      env:
        GIT_SECRET: ${{ inputs.secret }}
        GIT_REPO: ${{ inputs.repo || env.GITHUB_REPOSITORY }}
        DIGEST_SAVE_DIR: ${{ inputs.save }}
      run: |
        python ${{ github.action_path }}/app.py
      shell: bash

    - name: Push changes if there are changes to the data file
      run: |
        git config --local user.email "github-digest-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-digest-actions[bot]"
        git add -f ${{ inputs.save }}/digest.setting.json
        git commit --allow-empty -m "Update digest setting"
        git diff --quiet HEAD~ HEAD || git push
      shell: bash

